### ISSUE TITLE
Why the tempora dependency

### ISSUE THREAD

**Issue by Safihre** [jaraco/portend#4]
While I appreciate the strong focus you have on testing and putting core functionality in core packages, I really wonder if in the case of `tempora` for `portend` this might be a bit overkill.

All you really use it for is to check if `time_passed = time.now() - start_time` in the `occupied`/`free` checks.
Adding `tempora` also ads it's (in this case unused) dependency `pytz`.
Should super-simple Python-core functionality really require it's own package-dependency?

**Comment by jaraco** [comment]
You're right in that the core functionality almost implements what Stopwatch does... and that you can implement such a check with only slightly more complication (one additional in-line computation).

The advantage of the `Stopwatch` is that it encapsulates the functionality that doesn't exist in the core Python, that of setting a start time and computing the time elapsed since that start time. It prevents errors that one might accidentally make, such as perhaps writing `start_time - time.now()` or accidentally comparing `time.time()` with `time.now()` or [race conditions that may emerge when the local timezone changes during the loop](https://github.com/jaraco/tempora/issues/3). The boilerplate logic (set a start time, calculate distance from start time) is replaced by a tried and tested implementation.

I agree it's a small advantage and that the cost of the dependency may outweigh the advantages in the abstraction. For this project, the cost of the dependency is negligible as the dependencies are pure Python and the Python packaging infrastructure makes the dependency declaration and inclusion a trivial matter. I do have to acknowledge, though, that other package managers may not find the costs of managing dependencies as trivial as Python does.

But moreover, since the behavior is used more than once in the package (twice), the advantages are multiplied. And what's more, the use of such a library demonstrates the value that such behavior would have in the standard library (as I've used the Stopwatch in dozens of other projects).

As I look at it more, I realize there's even more boilerplate logic in the code that's repeated in both functions:

- inference of seconds from datetime.timedelta.
- default infinite timeout
- comparison of elapsed time to timeout

This behavior should additionally be encapsulated somewhere, and the tempora package seems like a good place to do it.

So we see another advantage of incorporating such a dependency even for a simple usage as above - it drastically reduces the burden of factoring out functionality for re-use in other projects, encouraging maximal re-use and limiting repetition and divergence.
