### ISSUE TITLE
find_available_local_port fails with OSError when IPv6 is not enabled

### ISSUE THREAD

**Issue by hawkway** [jaraco/portend#6]
I am trying to install portend (python2-portend) on Arch Linux and am running into the following error:

Does this have to do with me using IPv4? I have tried to enable IPv6 and try again to no avail. IPv6 modules are enabled by default in linux, so I am not sure if this is something I am doing wrong or not.

![screenshot_20170917_204630](https://user-images.githubusercontent.com/2049789/30526515-87f42e46-9be9-11e7-99e3-681dec03d8f9.png)

**Comment by Enverex** [comment]
Ditto. I'm on a machine with IPv6 disabled yet building fails with...
````
portend.py:162: in find_available_local_port
    sock = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
/usr/lib64/python3.6/socket.py:144: in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
E   OSError: [Errno 97] Address family not supported by protocol
````

**Comment by jaraco** [comment]
I think there are two issues at play here. In the first one, the tests are failing, but it's unclear why. We see the same test failures in Travis following the Nov updates. I'm tracking that in #8. So I'd like to adapt this ticket to focus on the failures when IPv6 is legitimately disabled and thus find_available_local_port fails with the OSError.

**Comment by jaraco** [comment]
First things first, I want to devise a way to simulate an environment without IPv6, preferably in a way that the test suite also conditionally exercise. Perhaps tox can create a virtualenv that's hacked to look like IPv6 is disabled. Or maybe pytest can monkeypatch the socket module to simulate IPv6 being disabled. Or maybe Travis-CI has a mechanism to disable IPv6 and we could run the tests in that additional environment.

Failing an environment in the test suite, I'd at least like a Dockerfile that creates the relevant environment, in which we could run the tests manually to validate IPv4-only behavior.

I think my preferred approach is the Travis-based one, because it's the least hacky but still provides continuous assurance of the expectation.

If someone would be willing to work on that, I'd appreciate it.

**Comment by jaraco** [comment]
I'm fairly certain these tests work when IPv6 is properly disabled. Now the tests are passing in Travis when IPv6 is disabled (and not half-broken). If there's another condition that the tests should honor or another mechanism to determine which protocols are available in various environments, I'm open to suggestions. But as implemented, the tests are passing on Linux, macOS, and Windows. I suggest updating your environment not to have a broken IPv6 stack.

**Comment by pawciobiel** [comment]
I was hoping you could add compatibility with systems that have ipv6 disabled. `find_available_local_port` won't work "when IPv6 is disabled properly" . IMO better way of disabling ipv6 is to remove ipv6 modules from the kernel and/or add to your boot loader `ipv6.disable=1` or build kernel without ipv6 support.

**Comment by jaraco** [comment]
In the above mentioned commit and releasing as portend 2.4, I've released a new technique that makes no mention of AF_INET. I believe this technique should address the issue. Since I'm unable to test, I'm pushing this change out in the blind. Please let me know if it doesn't solve the issue in your environment.
